"""Closed technology vocabulary for grounding checks.

Keep this list aligned with the skills the pipeline can verify. Matching is
case-insensitive on word boundaries; see shared/profile/grounding.py.
"""
KNOWN_TECH_VOCAB = [
    "devops",
    "kubernetes",
    "k8s",
    "docker",
    "terraform",
    "ansible",
    "aws",
    "azure",
    "gcp",
    "ci/cd",
    "jenkins",
    "gitlab",
    "github",
    "git",
    "python",
    "java",
    "go",
    "rust",
    "ruby",
    "scala",
    "javascript",
    "typescript",
    "microservices",
    "jira",
    "alm",
    "test automation",
    "istqb",
    "selenium",
    "rag",
    "llm",
    "langgraph",
    "flowise",
    "mcp",
    "linux",
    "bash",
    "rest",
    "api",
    "monitoring",
    "prometheus",
    "grafana",
    "mlflow",
    "pytorch",
    "tensorflow",
    "sql",
    "postgres",
    "redis",
    "kafka",
    "spring",
    "maven",
    "react",
    "node",
]
